### ISSUE TITLE
How do I set firebase in this project ?

### ISSUE THREAD

**Issue by rahulmool** [Foy5al/healthcare-service-app#1]
How do I set firebase in this project ? 
I modified this file
src/components/Login/Firebase/Firebase.config.js
But it's not updating in the firebase. What should I do?

**Comment by Foy5al** [comment]
Check the Hooks folder in the src directory of the Demo, where useFirebase.js is a configuration file. You can view a demonstration of how I added authentication to this project in this file, and useAuth.js is another file you should flow.
